# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_организация'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='организация',
            options={'ordering': ('id',), 'verbose_name': 'организация', 'verbose_name_plural': 'организации'},
        ),
    ]
