# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170303_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='задача',
            options={'ordering': ('дата_создания',), 'verbose_name': 'задача', 'verbose_name_plural': '_задачи'},
        ),
        migrations.AlterModelOptions(
            name='комментарий',
            options={'ordering': ('дата_создания',), 'verbose_name': 'комментарий', 'verbose_name_plural': '_комментарии'},
        ),
    ]
