# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170303_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Контрагент',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('наименование', models.CharField(max_length=100, verbose_name='наименование')),
                ('инн', models.CharField(max_length=12, verbose_name='инн')),
            ],
            options={
                'verbose_name_plural': 'контрагенты',
                'verbose_name': 'контрагент',
                'ordering': ('id',),
            },
        ),
    ]
