# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_контрагент'),
    ]

    operations = [
        migrations.AddField(
            model_name='контрагент',
            name='покупатель',
            field=models.BooleanField(default=False, verbose_name='покупатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='контрагент',
            name='поставщик',
            field=models.BooleanField(default=False, verbose_name='поставщик'),
            preserve_default=False,
        ),
    ]
