# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170303_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Договор',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('наименование', models.CharField(max_length=100, verbose_name='наименование')),
                ('номер', models.CharField(max_length=100, verbose_name='инн')),
                ('дата', models.DateField(verbose_name='дата')),
                ('контрагент', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Контрагент')),
                ('организация', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Организация')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name_plural': 'договоры',
                'verbose_name': 'договор',
            },
        ),
    ]
