# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_договор'),
    ]

    operations = [
        migrations.AddField(
            model_name='контрагент',
            name='картинка',
            field=models.ImageField(default=1, upload_to='', verbose_name='картинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='договор',
            name='контрагент',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Контрагент', verbose_name='контрагент'),
        ),
        migrations.AlterField(
            model_name='договор',
            name='номер',
            field=models.CharField(max_length=100, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='договор',
            name='организация',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Организация', verbose_name='организация'),
        ),
    ]
