# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170303_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='организация',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='картинка'),
            preserve_default=False,
        ),
    ]
